modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="spaz_craft"
version="1.0.0"
displayName="Spaz Craft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ALi, MCreator"

[[dependencies.spaz_craft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



